apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.config.map }}
data:
  {{ .Values.app.config.file }}: |-
    env: {{ .Values.env }}
    grpc:
      port: {{ .Values.grpc.port }}
    database:
      host: {{ .Values.database.host }}
      port: {{ .Values.database.port }}
      user: {{ .Values.database.user }}
      pass: {{ .Values.database.pass }}
      name: {{ .Values.database.name }}
    loki:
      host: {{ .Values.loki.host }}
      port: {{ .Values.loki.port }}
    services:
      products:
        host: {{ .Values.services.products.host }}
        port: {{ .Values.services.products.port }}
      authorization:
        host: {{ .Values.services.authorization.host }}
        port: {{ .Values.services.authorization.port }}