apiVersion: v1
kind: Service
metadata:
  name: eshop-mino-admin-service
spec:
  type: LoadBalancer
  selector:
    app: eshop-storage
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001