app:
  image: registry.gitlab.com/e-com-shop/backend/eshop-authorization-ms:dev
  name: auth-ms
  config:
    map: eshop-auth-config
    file: config_docker.yaml
  service:
    name: eshop-auth-service
env: local
grpc:
  port: 9091
port: ":8080"
database:
  host: eshop-pg-service
  port: 5432
  user: user
  pass: pass
  name: authservice
jwt:
  secret: secret
  ttl: 3600
loki:
  host: 213.226.125.222
  port: 3100