apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.postgres.pod }}
          image: {{ .Values.app.postgres.image }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.app.postgres.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.app.postgres.pass }}
          ports:
            - containerPort: {{ .Values.app.postgres.port}}
          volumeMounts:
            - name: {{ .Values.volumes.pg.name }}
              mountPath: /var/lib/postgresql/data

        - name: {{ .Values.app.redis.pod }}
          image: {{ .Values.app.redis.image }}
          command: [ "redis-server", "--requirepass", "{{.Values.app.redis.pass}}" ]
          ports:
            - containerPort: {{ .Values.app.redis.port }}
          volumeMounts:
            - name: {{ .Values.volumes.redis.name }}
              mountPath: /data

        - name: {{ .Values.app.minio.pod }}
          image: {{ .Values.app.minio.image }}
          command:
            - /bin/bash
            - -c
          args:
            - minio server /data --console-address :9001
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.app.minio.access_key }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.app.minio.secret_key }}
          volumeMounts:
            - name: {{ .Values.volumes.minio.name }}
              mountPath: /data
          ports:
            - containerPort: {{ .Values.app.minio.port }}
            - containerPort: 9001

      volumes:
        - name: {{ .Values.volumes.pg.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.pg.pvc }}
        - name: {{ .Values.volumes.redis.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.redis.pvc }}
        - name: {{ .Values.volumes.minio.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.minio.pvc }}

      imagePullSecrets:
        - name: yandex-cloud-registry