apiVersion: batch/v1
kind: Job
metadata:
  name: eshop-init-db
spec:
  template:
    metadata:
      name: eshop-init-db
    spec:
      containers:
        - name: init-db-products
          image: {{ .Values.app.postgres.image }}
          env:
            - name: PGPASSWORD
              value: {{ .Values.app.postgres.pass }}
          command: [ "psql", "-h", "eshop-pg-service", "-U", "user", "-d", "postgres", "-c", "CREATE DATABASE productsservice;" ]
        - name: init-db-auth
          image: {{ .Values.app.postgres.image }}
          env:
            - name: PGPASSWORD
              value: {{ .Values.app.postgres.pass }}
          command: [ "psql", "-h", "eshop-pg-service", "-U", "user", "-d", "postgres", "-c", "CREATE DATABASE authservice;" ]
        - name: init-db-orders
          image: {{ .Values.app.postgres.image }}
          env:
            - name: PGPASSWORD
              value: {{ .Values.app.postgres.pass }}
          command: [ "psql", "-h", "eshop-pg-service", "-U", "user", "-d", "postgres", "-c", "CREATE DATABASE ordersservice;" ]
      restartPolicy: Never
  backoffLimit: 4
