apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.volumes.pg.pvc}}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{.Values.volumes.pg.size}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.volumes.redis.pvc}}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{.Values.volumes.redis.size}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.volumes.minio.pvc}}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{.Values.volumes.minio.size}}