apiVersion: v1
kind: Secret
metadata:
  name: gitlab
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.gitlab.com": {
          "username": "wensiet",
          "password": "{{ .Values.gitlab.secret }}",
          "email": "wensietyt@gmail.com"
        }
      }
    }
