apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.postgres.service}}
spec:
  selector:
    app: {{.Values.app.name}}
  ports:
    - protocol: TCP
      port: {{.Values.app.postgres.port}}
      targetPort: {{.Values.app.postgres.port}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.redis.service}}
spec:
  selector:
    app: {{.Values.app.name}}
  ports:
    - protocol: TCP
      port: {{.Values.app.redis.port}}
      targetPort: {{.Values.app.redis.port}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.minio.service}}
spec:
  selector:
    app: {{.Values.app.name}}
  ports:
    - protocol: TCP
      port: {{.Values.app.minio.port}}
      targetPort: {{.Values.app.minio.port}}
