apiVersion: v1
kind: Service
metadata:
  name: eshop-pg-service
spec:
  selector:
    app: eshop-storage
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-redis-service
spec:
  selector:
    app: eshop-storage
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-minio-service
spec:
  selector:
    app: eshop-storage
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
