apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.config.map }}
data:
  {{ .Values.app.config.file }}: |-
    env: {{ .Values.env }}
    grpc:
      port: {{ .Values.grpc.port }}
    database:
      host: {{ .Values.database.host }}
      port: {{ .Values.database.port }}
      user: {{ .Values.database.user }}
      pass: {{ .Values.database.pass }}
      name: {{ .Values.database.name }}
    redis:
      host: {{ .Values.redis.host }}
      port: {{ .Values.redis.port }}
      pass: {{ .Values.redis.pass }}
      db: {{ .Values.redis.db }}
    loki:
      host: {{ .Values.loki.host }}
      port: {{ .Values.loki.port }}
    minio:
      host: {{ .Values.minio.host }}
      port: {{ .Values.minio.port }}
      access_key: {{ .Values.minio.access_key }}
      secret_key: {{ .Values.minio.secret_key }}
      use_ssl: {{ .Values.minio.use_ssl }}
      bucket: {{ .Values.minio.bucket }}
    jwt:
      secret: {{ .Values.jwt.secret }}
      ttl: {{ .Values.jwt.ttl }}
