apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.grpc.port }}
      targetPort: {{ .Values.grpc.port }}