apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.config.map }}
data:
  {{ .Values.app.config.file }}: |-
    env: {{ .Values.env }}
    port: {{ .Values.port }}
    database:
      host: {{ .Values.database.host }}
      port: {{ .Values.database.port }}
      user: {{ .Values.database.user }}
      pass: {{ .Values.database.pass }}
      name: {{ .Values.database.name }}
    jwt:
      secret: {{ .Values.jwt.secret }}
      ttl: {{ .Values.jwt.ttl }}
    loki:
      host: {{ .Values.loki.host }}
      port: {{ .Values.loki.port }}