app:
  image: registry.gitlab.com/e-com-shop/backend/eshop-products-ms:dev
  name: products-ms
  config:
    map: eshop-products-config
    file: config_docker.yaml
  service:
    name: eshop-products-service
env: local
grpc:
  port: 9090
database:
  host: eshop-pg-service
  port: 5432
  user: user
  pass: pass
  name: productsservice
redis:
  host: eshop-redis-service # DYNAMIC FIELD, now is: eshop-redis-service
  port: 6379
  pass: pass
  db: 0
loki:
  host: 213.226.125.222 # DYNAMIC FIELD, now is: 213.226.125.222
  port: 3100
minio:
  host: eshop-minio-service # DYNAMIC FIELD, now is: eshop-minio-service
  port: 9000
  access_key: username
  secret_key: password
  use_ssl: false
  bucket: products
jwt:
  secret: secret
  ttl: 3600