apiVersion: v1
kind: ConfigMap
metadata:
  name: eshop-nginx-config
data:
  nginx.conf: |-
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid;

    events {
      worker_connections 1024;
    }

      http {
      default_type application/octet-stream;

      log_format main '$remote_addr - $remote_user [$time_local] "$request" '
      '$status $body_bytes_sent "$http_referer" '
      '"$http_user_agent" "$http_x_forwarded_for"';

      access_log /var/log/nginx/access.log main;

      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;

      keepalive_timeout 65;

      gzip on;
      gzip_disable "msie6";

      server {
      listen 80;
      server_name example.com;
      root /var/www/html;

      location /api/v1/ {
      proxy_pass http://eshop-gateway-service:8000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }

      location /media/ {
        proxy_pass http://eshop-minio-service:9000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eshop-gateway-config
data:
  config.yaml: |-
    env: local
    port: 8000
    domain: http://localhost/media
    path: "/api/v1"
    sentry: https://667b4cfbf3b29df190748ccac1ee04d8@o4506655030378496.ingest.sentry.io/4506655032147968
    products:
      host: eshop-products-service
      port: 9090
    authorization:
      host: eshop-auth-service
      port: 9091
    loki:
      host: 213.226.125.222
      port: 3100
    redis:
      host: eshop-redis-service
      port: 6379
      db: 2
      password: pass

