apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-ms
  template:
    metadata:
      labels:
        app: gateway-ms
    spec:
      containers:
        - name: gateway-ms
          image: registry.gitlab.com/e-com-shop/backend/eshop-gateway-ms:dev
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: eshop-gateway-config
            items:
              - key: config.yaml
                path: config_docker.yaml
      imagePullSecrets:
        - name: gitlab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gateway
  labels:
    app: nginx-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-gateway
  template:
    metadata:
      labels:
        app: nginx-gateway
    spec:
      containers:
        - name: nginx-gateway
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/
      volumes:
        - name: nginx-config
          configMap:
            name: eshop-nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf