apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.gateway.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.gateway.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.app.gateway.name}}
    spec:
      containers:
        - name: {{ .Values.app.gateway.name }}
          image: {{ .Values.app.gateway.image }}
          ports:
            - containerPort: {{ .Values.port }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.app.config.name }}
            items:
              - key: {{ .Values.app.config.file }}
                path: {{ .Values.app.config.file }}
      imagePullSecrets:
        - name: gitlab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.nginx.name }}
  labels:
    app: {{ .Values.app.nginx.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.nginx.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.nginx.name }}
    spec:
      containers:
        - name: {{ .Values.app.nginx.name }}
          image: {{ .Values.app.nginx.image }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/
      volumes:
        - name: nginx-config
          configMap:
            name: eshop-nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
      imagePullSecrets:
        - name: yandex-cloud-registry