apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.nginx.service }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: {{ .Values.app.nginx.service }}.dev
      http:
        paths:
          - path: /api/v1/
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.app.gateway.service }}
                port:
                  number: {{ .Values.port }}
          - path: /media/
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.app.media.service }}
                port:
                  number: {{ .Values.app.media.port }}