apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.gateway.service }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.app.gateway.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      nodePort: {{ .Values.app.node_port }}