apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.gateway.service }}
spec:
  selector:
    app: {{ .Values.app.gateway.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.nginx.service }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.app.nginx.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80